config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: 'devise_customizations/registrations'
  }

  resources :users do
    member do
      get 'analytics_alias'
    end
  end

  namespace :admin do
    resources :users do
      member do
        get 'impersonate'
      end

      collection do
        get 'stop_impersonating'
      end
    end
  end

  authenticated :user do
    # root to: 'dashboard#show', as: :authenticated_root
    root to: 'high_voltage/pages#show', id: 'welcome', as: :authenticated_root
  end

  devise_scope :user do
    get 'sign-in',  to: 'devise/sessions#new'
    get 'sign-out', to: 'devise/sessions#destroy'
  end
  root 'high_voltage/pages#show', id: 'welcome'

  # API-specific routes
  namespace 'api' do
    namespace 'v1' do
      resources :users, except: [:new, :edit]
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  acts_as_token_authenticatable

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  before_create :generate_uuid

  # Permissions cascade/inherit through the roles listed below. The order of
  # this list is important, it should progress from least to most privelage
  ROLES = %i[admin accountant].freeze
  acts_as_user roles: ROLES
  roles ROLES

  validates :email,
            presence: true,
            format: /\A[-a-z0-9_+\.]+\@([-a-z0-9]+\.)+[a-z0-9]{2,8}\z/i,
            uniqueness: true

  # NOTE: these password validations won't run if the user has an invite token
  validates :password,
            presence: true,
            length: { within: 8..72 },
            confirmation: true,
            on: :create
  validates :password_confirmation,
            presence: true,
            on: :create

  def tester?
    (email =~ /(example.com|headway.io)$/).present?
  end

  private

  def generate_uuid
    loop do
      uuid = SecureRandom.uuid
      self.uuid = uuid
      break unless User.exists?(uuid: uuid)
    end
  end
end

# == Schema Information
#
# Table name: users
#
#  authentication_token   :string(30)
#  created_at             :datetime         not null
#  current_sign_in_at     :datetime
#  current_sign_in_ip     :inet
#  email                  :string           default(""), not null
#  encrypted_password     :string           default(""), not null
#  first_name             :string
#  id                     :integer          not null, primary key
#  last_name              :string
#  last_sign_in_at        :datetime
#  last_sign_in_ip        :inet
#  remember_created_at    :datetime
#  reset_password_sent_at :datetime
#  reset_password_token   :string
#  roles_mask             :integer
#  sign_in_count          :integer          default(0), not null
#  updated_at             :datetime         not null
#  uuid                   :string
#
# Indexes
#
#  index_users_on_authentication_token  (authentication_token) UNIQUE
#  index_users_on_email                 (email) UNIQUE
#  index_users_on_reset_password_token  (reset_password_token) UNIQUE
#

app/controllers/admin/users_controller.rb
module Admin
  class UsersController < AdminController
    skip_before_action :require_admin!, only: [:stop_impersonating]
    respond_to :html, :json

    def index
      @users = User.all
      respond_with(@users)
    end

    def new
      @user = User.new
    end

    def create
      @user = User.new(user_params)
      if @user.save
        redirect_to admin_user_path(@user)
      else
        flash.now[:alert] = @user.errors.full_messages.join(', ')
        render :new
      end
    end

    def show
      @user = User.find(params[:id])
    end

    def impersonate
      user = User.find(params[:id])
      track_impersonation(user, 'Start')
      impersonate_user(user)
      redirect_to root_path
    end

    def stop_impersonating
      track_impersonation(current_user, 'Stop')
      stop_impersonating_user
      redirect_to admin_users_path
    end

    private

    def user_params
      params.require(:user).permit(:first_name, :last_name, :email, :password,
                                   :password_confirmation, roles: [])
    end

    def track_impersonation(user, status)
      analytics_track(
        true_user,
        "Impersonation #{status}",
        impersonated_user_id: user.id,
        impersonated_user_email: user.email,
        impersonated_by_email: true_user.email,
      )
    end
  end
end

app/controllers/api/v1/users_controller.rb
module Api
  module V1
    class UsersController < BaseApiController
      authorize_resource
      respond_to :json

      def index
        respond_with(User.all)
      end

      def show
        @user = User.find(params[:id])
        respond_with(@user)
      end

      def create
        @user = User.new(user_params)

        if @user.save
          respond_with @user do |format|
            format.json { render json: @user, status: :created }
          end
        else
          respond_with_errors(@user)
        end
      end

      def update
        @user = User.find(params[:id])

        if @user.update_attributes(user_params)
          respond_with(@user)
        else
          respond_with_errors(@user)
        end
      end

      def destroy
        user = User.find(params[:id])

        if user.destroy
          render json: {}, status: 204
        else
          render json: {}, status: 500
        end
      end

      private

      def user_params
        params.require(:user).permit(:first_name, :last_name, :email,
                                     :password, :password_confirmation)
      end
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  # https://github.com/CanCanCommunity/cancancan/wiki/authorizing-controller-actions
  # load_and_authorize_resource only: []
  skip_authorization_check only: [:analytics_alias]

  def analytics_alias
    # view file has JS that will identify the anonymous user through segment
    # after registration via "after devise registration path"
  end
end

app/views/admin/users/index.html.slim
h1
  | Listing Users
table.users-table
  thead
    tr
      th
        | First Name
      th
        | Last Name
      th
        | Email
      th
        | Roles
      th
      th
      th
  tbody
    - @users.each do |user|
      tr
        td
          = user.first_name
        td
          = user.last_name
        td
          = link_to user.email, impersonate_admin_user_path(user)
        td
          = user.roles.map(&:to_s).join(', ')
        td
          = link_to 'Show', user
        td
          = link_to 'Edit', edit_user_path(user)
        td
          = link_to 'Destroy', user, data: { confirm: 'Are you sure?' }, method: :delete
br

app/views/admin/users/new.html.slim
h1
  | New User
div
  = simple_form_for(@user, url: admin_users_path) do |f|
    .form-inputs
      = f.label :first_name, "First Name"
      = f.text_field :first_name

      = f.label :last_name, "Last Name"
      = f.text_field :last_name

      = f.label :email, "E-Mail Address"
      = f.text_field :email

      = f.label :roles, "Roles"
      - User::ROLES.each do |role|
        .checkboxes
          = check_box_tag "user[roles][#{role}]", role, @user.roles.include?(role), {name: 'user[roles][]'}
          = label_tag "user_roles_#{role}", role.to_s.humanize
        = hidden_field_tag "user[roles][]", ""

      = f.label :password, "Password"
      = f.password_field :password

      = f.label :password_confirmation, "Password Confirmation"
      = f.password_field :password_confirmation
    .form-actions
      = f.submit "Create User"

app/views/admin/users/show.html.slim
h1 
  = "#{@user.first_name} #{@user.last_name}"
p
  = @user.email